# Generated by Django 4.1.1 on 2022-09-25 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_sum', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('init', 'Init'), ('paid', 'Paid')], default='init', max_length=20)),
                ('payment_type', models.CharField(choices=[('cash', 'cash'), ('non_cash', 'Non cash')], default='non_cash', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
