# Generated by Django 4.1.1 on 2022-09-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='sum',
            new_name='payment_sum',
        ),
    ]
