# Generated by Django 4.1.1 on 2022-09-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'cash'), ('non_cash', 'Non cash')], default='non_cash', max_length=20),
        ),
    ]
