# Generated by Django 4.1.1 on 2022-09-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('init', 'Init'), ('waiting', 'Waiting'), ('paid', 'Paid')], default='init', max_length=20),
        ),
    ]
