# Generated by Django 4.1.1 on 2022-09-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('init', 'Init'), ('paid', 'Paid')], default='init', max_length=20),
        ),
    ]
