# Generated by Django 4.1.1 on 2022-09-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('init', 'Init'), ('in_progress', 'In progress'), ('complete', 'Complete')], default='init', max_length=20),
        ),
    ]
