# Generated by Django 4.1.1 on 2022-09-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_approved_at_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sum',
            new_name='order_sum',
        ),
    ]
