# Generated by Django 4.1.1 on 2022-09-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_approved_at_order_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('init', 'Init'), ('confirmed', 'Confirmed')], default='init', max_length=20),
        ),
    ]
